### ISSUE TITLE
Startup error in Windows-installed Document Archiver

### ISSUE THREAD

**Issue by Dansoftowner** [Document-Archiver/com.sophisticatedapps.archiving.document-archiver#3]
Hi, 

I installed Document Archiver by the Windows installer you provided.
When I launch the appication, the file-chooser shows up but then this dialog occurs:
![screenshot](https://user-images.githubusercontent.com/49782833/114847162-b1b9a900-9ddd-11eb-8f5f-1cb6bed92694.png)

Stacktrace:
```
java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: java/util/logging/Logger
	at com.sun.jna.Structure.<clinit>(Structure.java:114)
	at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVersionOrGreater(VersionHelpers.java:59)
	at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVistaOrGreater(VersionHelpers.java:127)
	at oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:105)
	at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:107)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:100)
	at com.jthemedetecor.OsInfo.<clinit>(OsInfo.java:16)
	at com.jthemedetecor.OsThemeDetector.getDetector(OsThemeDetector.java:24)
	at com.sophisticatedapps.archiving.documentarchiver.util.ThemeUtil.<clinit>(ThemeUtil.java:17)
	at com.sophisticatedapps.archiving.documentarchiver.App.start(App.java:113)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:474)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	... 1 more
Caused by: java.lang.ClassNotFoundException: java.util.logging.Logger
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 20 more

```

**Comment by Dansoftowner** [comment]
I can see in the stacktrace that it's somehow related to `jSystemThemeDetector` but the jar file is working perfectly. 
Maybe something is wrong with the installation process..

**Comment by stephansann** [comment]
Hi Daniel
Thanks for the report.
I guess it will have something to do with modularity (module-info.java).
I will have a look into that.

BTW: Have you ever considered modularity for jSystemThemeDetector and/or PDFViewerFX? I had some problems using jlink because of the projects' automatic module nature before I decided to go with install4j.

**Comment by Dansoftowner** [comment]
Thanks for mentioning modularity support, I will do something about it :)

**Comment by stephansann** [comment]
Hi again, Daniel

I now built a Windows Installer for the current SNAPSHOT-version (which includes jSystemThemeDetector 3.1) and it seems to be running fine on my virtual Windows.
I put it here for a download:
https://www.sophisticatedapps.com/downloads/DocumentArchiver_windows-x64_1_5_0-SNAPSHOT.exe

Could you give it a spin and tell me if it's okay for you, too?
Please make sure to deinstall the old broken version first (a deinstaller should be found in Settings/Apps).

Thanks and best regards
Stephan

**Comment by Dansoftowner** [comment]
Hi @stephansann ,

It's working now perfectly! :)

Best regards
Daniel
