### ISSUE TITLE
Ability for automatic restart when switching languages

### ISSUE THREAD

**Issue by Dansoftowner** [Document-Archiver/com.sophisticatedapps.archiving.document-archiver#6]
Hi!

I tried switching languages, which works perfectly fine.
My suggestion is that you could give the user the ability to restart the application immediately in this dialog:
![Lang switching dialog](https://user-images.githubusercontent.com/49782833/115015254-aafd6580-9eb3-11eb-83fc-7cfebe94e358.png)

You can implement it using [Restart4j](https://github.com/Dansoftowner/Restart4j), it works no matter how the application is bundled (even if your java app runs for example as a native Windows application).

```
ApplicationRestart.builder()
                    .terminationPolicy(javafx.application.Platform::exit)
                    .build().restartApp();
```
Here is my application using it:

![LibraryAppRestart](https://user-images.githubusercontent.com/49782833/115015676-527a9800-9eb4-11eb-83fd-2549ac9acd95.gif)

Hope you found this enhancement request useful :)

Daniel

**Comment by stephansann** [comment]
Looks interesting. I will have a look at it. Thanks for the suggestion 🙏🏻

**Comment by stephansann** [comment]
Tried this:

```
                    Optional<ButtonType> tmpRestartResult =
                            dialogProvider.providePreferencesChangedAlert().showAndWait();

                    // Restart?
                    tmpRestartResult.ifPresent(aRestartButtonType -> {

                        if (ButtonType.YES == aRestartButtonType) {

                            ApplicationRestart.builder().terminationPolicy(javafx.application.Platform::exit)
                                    .build().restartApp();
                        }
                    });
```

got that:

```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1862)
	at javafx.fxml/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1729)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.controls/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1385)
	at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1338)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1851)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1859)
	... 40 more
Caused by: java.lang.IllegalArgumentException: Empty command
	at java.base/java.lang.Runtime.exec(Runtime.java:410)
	at java.base/java.lang.Runtime.exec(Runtime.java:313)
	at Restart4j@1.0/com.restart4j.ApplicationRestart.restartApp(ApplicationRestart.java:65)
	at DocumentArchiver/com.sophisticatedapps.archiving.documentarchiver.controller.MenuBarController.lambda$handlePreferencesMenuItemAction$0(MenuBarController.java:128)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at DocumentArchiver/com.sophisticatedapps.archiving.documentarchiver.controller.MenuBarController.lambda$handlePreferencesMenuItemAction$1(MenuBarController.java:123)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at DocumentArchiver/com.sophisticatedapps.archiving.documentarchiver.controller.MenuBarController.handlePreferencesMenuItemAction(MenuBarController.java:105)
	... 51 more
```

Any ideas?

Thanks and best regards
Stephan

**Comment by Dansoftowner** [comment]
Is this issue occurs on MacOS?

**Comment by stephansann** [comment]
Yes, the issue appeared on my Mac.

Anyhow I can cross-check with Windows if you think there could be a difference.

**Comment by stephansann** [comment]
Opened a bug for this:
https://github.com/Dansoftowner/Restart4j/issues/1

**Comment by stephansann** [comment]
Coming in version 1.6.0.
